#!/usr/bin/env python3
"""
Generate hard scenario dataset for EM-002.
Target: ≥60 scenarios, ≥150 queries (5 scenarios * 12 categories * 3 queries = 180)
"""
import json
from pathlib import Path

HARD_DIR = Path("evals/datasets_hard")
HARD_DIR.mkdir(exist_ok=True)

def mem(content, kind="fact", age_days=30, importance=0.7, domain="General", scope_user=""):
    return {"content": content, "kind": kind, "age_days": age_days,
            "importance": importance, "domain": domain, "scope_user": scope_user}

def turn(query, expect_ids=None, expect_substrings=None, must_not=None):
    return {"query": query, "expect_ids": expect_ids or [],
            "expect_substrings": expect_substrings or [], "must_not": must_not or []}

N = {"generator": "filler", "count": 20, "seed": 42}

# ─── Paraphrase (5 scenarios) ───
paraphrase = [
    {"id": "paraphrase_editor_01", "category": "paraphrase",
     "memories": [mem("The user prefers Neovim for daily coding tasks", kind="preference", age_days=30, importance=0.7, domain="Tools")],
     "noise": N,
     "turns": [turn("what editor do I code in?", ["$0"], ["Neovim"]),
               turn("which text editor do I use most?", ["$0"], ["Neovim"]),
               turn("my main coding tool is?", ["$0"], ["Neovim"])]},
    {"id": "paraphrase_language_01", "category": "paraphrase",
     "memories": [mem("The user's primary language for documentation is English", kind="fact", age_days=45, importance=0.8, domain="Communication")],
     "noise": {"generator": "filler", "count": 20, "seed": 43},
     "turns": [turn("what language do I write docs in?", ["$0"], ["English"]),
               turn("my documentation language is?", ["$0"], ["English"]),
               turn("in what language are my documents written?", ["$0"], ["English"])]},
    {"id": "paraphrase_notebook_01", "category": "paraphrase",
     "memories": [mem("The user journals in a physical Moleskine notebook", kind="preference", age_days=90, importance=0.6, domain="Personal")],
     "noise": {"generator": "filler", "count": 20, "seed": 46},
     "turns": [turn("where does the user journal?", ["$0"], ["Moleskine"]),
               turn("what notebook brand does the user use?", ["$0"], ["Moleskine"]),
               turn("which physical notebook does the user write in?", ["$0"], ["Moleskine"])]},
    {"id": "paraphrase_taking_notes_01", "category": "paraphrase",
     "memories": [mem("The user records meeting notes in Obsidian", kind="fact", age_days=40, importance=0.75, domain="Tools")],
     "noise": {"generator": "filler", "count": 20, "seed": 47},
     "turns": [turn("where do the meeting notes live?", ["$0"], ["Obsidian"]),
               turn("which app holds meeting notes?", ["$0"], ["Obsidian"]),
               turn("what tool does the user use for meeting notes?", ["$0"], ["Obsidian"])]},
    {"id": "paraphrase_email_client_01", "category": "paraphrase",
     "memories": [mem("The user checks email via the himalaya CLI as a fallback to gws", kind="preference", age_days=50, importance=0.6, domain="Communication")],
     "noise": {"generator": "filler", "count": 20, "seed": 48},
     "turns": [turn("what fallback email client does the user use?", ["$0"], ["himalaya"]),
               turn("which CLI tool handles email fallback?", ["$0"], ["himalaya"]),
               turn("what is the IMAP fallback for gws?", ["$0"], ["himalaya"])]},
]

# ─── Ageing (5 scenarios) ───
ageing = [
    {"id": "ageing_name_30d_01", "category": "ageing",
     "memories": [mem("The user's current display name is Alex Rivera", kind="profile", age_days=30, importance=0.8, domain="People"),
                  mem("The user previously went by the name Alexander", kind="fact", age_days=5, importance=0.6, domain="People")],
     "noise": {"generator": "filler", "count": 20, "seed": 101},
     "turns": [turn("what is the user's display name?", ["$0"], ["Alex Rivera"]),
               turn("what name do I currently use?", ["$0"], ["Alex Rivera"]),
               turn("my current display name is?", ["$0"], ["Alex Rivera"])]},
    {"id": "ageing_name_120d_01", "category": "ageing",
     "memories": [mem("The user's current display name is Alex Rivera", kind="profile", age_days=120, importance=0.8, domain="People"),
                  mem("The user previously went by the name Alexander", kind="fact", age_days=5, importance=0.6, domain="People")],
     "noise": {"generator": "filler", "count": 20, "seed": 102},
     "turns": [turn("what is the user's display name?", ["$0"], ["Alex Rivera"]),
               turn("what name do I currently use?", ["$0"], ["Alex Rivera"]),
               turn("my current display name is?", ["$0"], ["Alex Rivera"])]},
    {"id": "ageing_city_30d_01", "category": "ageing",
     "memories": [mem("The user lives in Cape Town, South Africa", kind="fact", age_days=30, importance=0.9, domain="People"),
                  mem("The user previously resided in Johannesburg", kind="fact", age_days=10, importance=0.7, domain="People")],
     "noise": {"generator": "filler", "count": 20, "seed": 104},
     "turns": [turn("where does the user live?", ["$0"], ["Cape Town"]),
               turn("what city am I based in?", ["$0"], ["Cape Town"]),
               turn("my location is?", ["$0"], ["Cape Town"])]},
    {"id": "ageing_city_120d_01", "category": "ageing",
     "memories": [mem("The user lives in Cape Town, South Africa", kind="fact", age_days=120, importance=0.9, domain="People"),
                  mem("The user previously resided in Johannesburg", kind="fact", age_days=10, importance=0.7, domain="People")],
     "noise": {"generator": "filler", "count": 20, "seed": 105},
     "turns": [turn("where does the user live?", ["$0"], ["Cape Town"]),
               turn("what city am I based in?", ["$0"], ["Cape Town"]),
               turn("my location is?", ["$0"], ["Cape Town"])]},
    {"id": "ageing_name_400d_01", "category": "ageing",
     "memories": [mem("The user's current display name is Alex Rivera", kind="profile", age_days=400, importance=0.8, domain="People"),
                  mem("The user previously went by the name Alexander", kind="fact", age_days=5, importance=0.6, domain="People")],
     "noise": {"generator": "filler", "count": 20, "seed": 103},
     "turns": [turn("what is the user's display name?", ["$0"], ["Alex Rivera"]),
               turn("what name do I currently use?", ["$0"], ["Alex Rivera"]),
               turn("my current display name is?", ["$0"], ["Alex Rivera"])]},
]

# ─── Update (5 scenarios) ───
update = [
    {"id": "update_port_01", "category": "update",
     "memories": [mem("The API gateway used to listen on port 8080 behind the load balancer during early bringup", kind="fact", age_days=200, importance=0.7, domain="Infrastructure"),
                  mem("Since the migration the API gateway listens on port 9090 with TLS termination", kind="fact", age_days=2, importance=0.7, domain="Infrastructure")],
     "noise": {"generator": "filler", "count": 120, "seed": 11},
     "turns": [turn("which port does the API gateway listen on now?", ["$1"], ["9090"], ["$noise"]) for _ in range(0)] +
              [turn("which port does the API gateway listen on now?", ["$1"], ["9090"]),
               turn("what is the current API gateway port?", ["$1"], ["9090"]),
               turn("which port is the API gateway bound to today?", ["$1"], ["9090"])]},
    {"id": "update_preference_01", "category": "update",
     "memories": [mem("The user preferred red notification badges on the dashboard", kind="preference", age_days=180, importance=0.6, domain="Preferences"),
                  mem("The user now prefers blue notification badges on the dashboard after the redesign", kind="preference", age_days=1, importance=0.6, domain="Preferences")],
     "noise": {"generator": "filler", "count": 120, "seed": 13},
     "turns": [turn("what color notification badges does the user prefer?", ["$1"], ["blue"]),
               turn("what is my current notification badge preference?", ["$1"], ["blue"]),
               turn("which badge color do I prefer after the redesign?", ["$1"], ["blue"])]},
    {"id": "update_theme_01", "category": "update",
     "memories": [mem("The user's desktop theme was set to dark mode with blue accents", kind="preference", age_days=100, importance=0.7, domain="Preferences"),
                  mem("The user switched to a light theme with green accents after the UI refresh", kind="preference", age_days=3, importance=0.7, domain="Preferences")],
     "noise": {"generator": "filler", "count": 20, "seed": 111},
     "turns": [turn("what is the user's current desktop theme?", ["$1"], ["light", "green"]),
               turn("which theme and accent colors do I use now?", ["$1"], ["light", "green"]),
               turn("what did the user change their desktop theme to?", ["$1"], ["light", "green"])]},
    {"id": "update_email_01", "category": "update",
     "memories": [mem("The user's primary email is gws at work@company.com", kind="preference", age_days=300, importance=0.9, domain="Communication"),
                  mem("The email was changed to gws at personal@newdomain.com last week", kind="preference", age_days=5, importance=0.8, domain="Communication")],
     "noise": {"generator": "filler", "count": 120, "seed": 12},
     "turns": [turn("what is the user's email address?", ["$1"], ["personal@newdomain.com"]),
               turn("what email does the user use for gws?", ["$1"], ["personal@newdomain.com"]),
               turn("what was the recent email change?", ["$1"], ["personal@newdomain.com"])]},
    {"id": "update_phone_01", "category": "update",
     "memories": [mem("The Signal phone number is +27 82 000 0001", kind="preference", age_days=200, importance=0.9, domain="Communication"),
                  mem("The Signal phone number was updated to +27 00 000 0000 for security reasons", kind="preference", age_days=10, importance=0.9, domain="Communication")],
     "noise": {"generator": "filler", "count": 120, "seed": 16},
     "turns": [turn("what is the Signal phone number?", ["$1"], ["+27 00 000 0000"]),
               turn("what number is used for Signal delivery?", ["$1"], ["+27 00 000 0000"]),
               turn("what was the phone number changed to recently?", ["$1"], ["+27 00 000 0000"])]},
]

# ─── Contradiction (5 scenarios) ───
contradiction = [
    {"id": "contradiction_fact_01", "category": "contradiction",
     "memories": [mem("The project deadline is Friday, June 14", kind="fact", age_days=5, importance=0.9, domain="Work"),
                  mem("The project deadline was moved to Monday, June 17", kind="fact", age_days=2, importance=0.9, domain="Work")],
     "noise": {"generator": "filler", "count": 20, "seed": 201},
     "turns": [turn("what is the project deadline?", ["$1"], ["June 17"]),
               turn("when is the deadline for the project?", ["$1"], ["June 17"]),
               turn("what date did we set for the project completion?", ["$1"], ["June 17"])]},
    {"id": "contradiction_policy_01", "category": "contradiction",
     "memories": [mem("The company policy allows remote work up to 3 days per week", kind="fact", age_days=30, importance=0.8, domain="Policy"),
                  mem("As of last week, the company policy requires all work to be done from the office", kind="fact", age_days=1, importance=0.9, domain="Policy")],
     "noise": {"generator": "filler", "count": 20, "seed": 202},
     "turns": [turn("what is the current company policy on remote work?", ["$1"], ["office"]),
               turn("am I allowed to work remotely under current policy?", ["$1"], ["office"]),
               turn("what does the policy say about remote work today?", ["$1"], ["office"])]},
    {"id": "contradiction_schedule_01", "category": "contradiction",
     "memories": [mem("The team meeting is scheduled for Tuesday at 10:00 AM", kind="fact", age_days=15, importance=0.8, domain="Work"),
                  mem("The team meeting was rescheduled to Thursday at 2:00 PM", kind="fact", age_days=2, importance=0.9, domain="Work")],
     "noise": {"generator": "filler", "count": 20, "seed": 203},
     "turns": [turn("what time is our team meeting?", ["$1"], ["Thursday", "2:00 PM"]),
               turn("when does the team meeting occur?", ["$1"], ["Thursday", "2:00 PM"]),
               turn("what is the scheduled time for our team meeting?", ["$1"], ["Thursday", "2:00 PM"])]},
    {"id": "contradiction_address_01", "category": "contradiction",
     "memories": [mem("The company's registered address is 123 Main Street, Johannesburg", kind="fact", age_days=200, importance=0.7, domain="Company"),
                  mem("The new office address is 456 Park Avenue, Sandton", kind="fact", age_days=5, importance=0.9, domain="Company")],
     "noise": {"generator": "filler", "count": 20, "seed": 204},
     "turns": [turn("what is our company address?", ["$1"], ["Park Avenue", "Sandton"]),
               turn("where is the office located now?", ["$1"], ["Park Avenue", "Sandton"]),
               turn("what is the current company address?", ["$1"], ["Park Avenue", "Sandton"])]},
    {"id": "contradiction_manager_01", "category": "contradiction",
     "memories": [mem("Sarah Chen is the team lead for the analytics group", kind="fact", age_days=40, importance=0.8, domain="People"),
                  mem("The management changed — David Park is now the analytics team lead", kind="fact", age_days=3, importance=0.9, domain="People")],
     "noise": {"generator": "filler", "count": 20, "seed": 205},
     "turns": [turn("who is the analytics team lead?", ["$1"], ["David Park"]),
               turn("who manages the analytics group now?", ["$1"], ["David Park"]),
               turn("what is the current team lead for analytics?", ["$1"], ["David Park"])]},
]

# ─── Multi-user (5 scenarios) ───
multi_user = [
    {"id": "multi_user_private_01", "category": "multi_user",
     "memories": [mem("User alice's SSH private key is stored in ~/.ssh/id_rsa_alice", kind="fact", age_days=60, importance=0.95, domain="Credentials", scope_user="alice"),
                  mem("User bob's SSH private key is stored in ~/.ssh/id_rsa_bob", kind="fact", age_days=60, importance=0.95, domain="Credentials", scope_user="bob")],
     "noise": {"generator": "filler", "count": 20, "seed": 401},
     "turns": [turn("what is alice's SSH private key path?", ["$0"], ["id_rsa_alice"]),
               turn("where does alice keep her SSH private key?", ["$0"], ["id_rsa_alice"]),
               turn("what is the file path for alice's SSH key?", ["$0"], ["id_rsa_alice"])]},
    {"id": "multi_user_preference_01", "category": "multi_user",
     "memories": [mem("User charlie prefers dark mode in all applications", kind="preference", age_days=45, importance=0.8, domain="Preferences", scope_user="charlie"),
                  mem("User dave prefers light mode in all applications", kind="preference", age_days=45, importance=0.8, domain="Preferences", scope_user="dave")],
     "noise": {"generator": "filler", "count": 20, "seed": 402},
     "turns": [turn("what is charlie's UI theme preference?", ["$0"], ["dark"]),
               turn("does charlie use dark or light mode?", ["$0"], ["dark"]),
               turn("what color scheme does charlie prefer?", ["$0"], ["dark"])]},
    {"id": "multi_user_contact_01", "category": "multi_user",
     "memories": [mem("User eve's emergency contact is her sister at +27 82 123 4567", kind="fact", age_days=30, importance=0.9, domain="Personal", scope_user="eve"),
                  mem("User frank's emergency contact is his brother at +27 71 987 6543", kind="fact", age_days=30, importance=0.9, domain="Personal", scope_user="frank")],
     "noise": {"generator": "filler", "count": 20, "seed": 403},
     "turns": [turn("what is eve's emergency contact number?", ["$0"], ["+27 82 123 4567"]),
               turn("what is frank's emergency contact?", ["$0"], ["+27 71 987 6543"]),
               turn("who should I call in case of emergency for eve?", ["$0"], ["+27 82 123 4567"])]},
    {"id": "multi_user_shared_01", "category": "multi_user",
     "memories": [mem("Dana and Ufonik share a wedding planning vault under Projects/Wedding", kind="fact", age_days=40, importance=0.8, domain="Projects", scope_user="Dana Ufonik"),
                  mem("The event date is set for June 1, 2025", kind="fact", age_days=20, importance=0.9, domain="Projects", scope_user="Dana Ufonik")],
     "noise": {"generator": "filler", "count": 20, "seed": 404},
     "turns": [turn("what is in the shared wedding vault?", ["$0", "$1"], ["wedding planning", "June 1, 2025"]),
               turn("who shares the wedding vault?", ["$0"], ["Dana", "Ufonik"]),
               turn("when is the wedding?", ["$1"], ["June 1, 2025"])]},
    {"id": "multi_user_separate_01", "category": "multi_user",
     "memories": [mem("Ufonik uses EntropicMem as the sole memory provider", kind="fact", age_days=5, importance=0.9, domain="System", scope_user="Ufonik"),
                  mem("Dana uses a separate Obsidian-only vault for personal notes", kind="fact", age_days=5, importance=0.7, domain="System", scope_user="Dana")],
     "noise": {"generator": "filler", "count": 20, "seed": 405},
     "turns": [turn("what memory system does Ufonik use?", ["$0"], ["EntropicMem"]),
               turn("what does Dana use for her notes?", ["$1"], ["Obsidian"]),
               turn("how do Ufonik and Dana differ on memory?", ["$0", "$1"], ["EntropicMem", "Obsidian"])]},
]

# ─── Multimodal (5 scenarios) ───
multimodal = [
    {"id": "multimodal_list_01", "category": "multimodal",
     "memories": [mem("The user shared a shopping list: [\"milk\", \"eggs\", \"bread\"]", kind="fact", age_days=5, importance=0.6, domain="Personal")],
     "noise": {"generator": "filler", "count": 20, "seed": 501},
     "turns": [turn("what items are on the user's shopping list?", ["$0"], ["milk", "eggs", "bread"]),
               turn("what did the user buy at the store?", ["$0"], ["milk", "eggs", "bread"]),
               turn("what was in the user's recent history as a list?", ["$0"], ["milk", "eggs", "bread"])]},
    {"id": "multimodal_list_02", "category": "multimodal",
     "memories": [mem("The user's TODO items are: [\"finish report\", \"call client\", \"update docs\"]", kind="fact", age_days=10, importance=0.7, domain="Work")],
     "noise": {"generator": "filler", "count": 20, "seed": 502},
     "turns": [turn("what are the user's current TODO items?", ["$0"], ["finish report", "call client", "update docs"]),
               turn("what tasks does the user need to complete?", ["$0"], ["finish report", "call client", "update docs"]),
               turn("what is the user's task list?", ["$0"], ["finish report", "call client", "update docs"])]},
    {"id": "multimodal_list_03", "category": "multimodal",
     "memories": [mem("The user's groceries for the week are: [\"apples\", \"bananas\", \"oranges\", \"spinach\"]", kind="fact", age_days=15, importance=0.65, domain="Personal")],
     "noise": {"generator": "filler", "count": 20, "seed": 503},
     "turns": [turn("what are the user's groceries for the week?", ["$0"], ["apples", "bananas", "oranges", "spinach"]),
               turn("what did the user buy for groceries this week?", ["$0"], ["apples", "bananas", "oranges", "spinach"]),
               turn("what is in the user's weekly grocery list?", ["$0"], ["apples", "bananas", "oranges", "spinach"])]},
    {"id": "multimodal_image_01", "category": "multimodal",
     "memories": [mem("Screenshot of the Document showing Acme revenue at R10K/month", kind="fact", age_days=5, importance=0.8, domain="Finance"),
                  mem("The budget uses Alpha/Beta/Gamma accounts for transactions", kind="fact", age_days=5, importance=0.7, domain="Finance")],
     "noise": {"generator": "filler", "count": 20, "seed": 504},
     "turns": [turn("what does the budget screenshot show?", ["$0"], ["R10K", "Acme"]),
               turn("which accounts are in the budget?", ["$1"], ["FP", "Beta", "Gamma"]),
               turn("what amount is in the budget?", ["$0"], ["R10K"])]},
    {"id": "multimodal_terminal_01", "category": "multimodal",
     "memories": [mem("Terminal output shows git worktree list with 3 active worktrees", kind="fact", age_days=1, importance=0.8, domain="System"),
                  mem("The EM-005 worktree commit hash starts with b7a88a4", kind="fact", age_days=1, importance=0.7, domain="System")],
     "noise": {"generator": "filler", "count": 20, "seed": 505},
     "turns": [turn("how many worktrees are active?", ["$0"], ["3"]),
               turn("what is the EM-005 commit prefix?", ["$1"], ["b7a88a4"]),
               turn("what does git show for active worktrees?", ["$0"], ["3"])]},
]

# ─── Procedural (5 scenarios) ───
procedural = [
    {"id": "procedural_deploy_01", "category": "procedural",
     "memories": [mem("To deploy staging: 1) push to main, 2) run deploy-staging.sh, 3) verify health check", kind="fact", age_days=20, importance=0.9, domain="Work")],
     "noise": {"generator": "filler", "count": 20, "seed": 601},
     "turns": [turn("how do I deploy staging?", ["$0"], ["push to main", "deploy-staging.sh", "verify health check"]),
               turn("what are the steps to deploy the staging environment?", ["$0"], ["push to main", "deploy-staging.sh", "verify health check"]),
               turn("what is the procedure for deploying staging?", ["$0"], ["push to main", "deploy-staging.sh", "verify health check"])]},
    {"id": "procedural_backup_01", "category": "procedural",
     "memories": [mem("Backup procedure: 1) snapshot the volume, 2) copy to backup server, 3) verify checksum", kind="fact", age_days=30, importance=0.85, domain="Work")],
     "noise": {"generator": "filler", "count": 20, "seed": 602},
     "turns": [turn("how do I perform a backup?", ["$0"], ["snapshot the volume", "copy to backup server", "verify checksum"]),
               turn("what are the steps for backing up data?", ["$0"], ["snapshot the volume", "copy to backup server", "verify checksum"]),
               turn("what is the backup procedure?", ["$0"], ["snapshot the volume", "copy to backup server", "verify checksum"])]},
    {"id": "procedural_build_01", "category": "procedural",
     "memories": [mem("To build the project: 1) run ./configure, 2) make, 3) make install", kind="fact", age_days=25, importance=0.8, domain="Work")],
     "noise": {"generator": "filler", "count": 20, "seed": 603},
     "turns": [turn("how do I build the project from source?", ["$0"], ["./configure", "make", "make install"]),
               turn("what are the steps to build this project?", ["$0"], ["./configure", "make", "make install"]),
               turn("what is the build procedure for this project?", ["$0"], ["./configure", "make", "make install"])]},
    {"id": "procedural_git_01", "category": "procedural",
     "memories": [mem("The git workflow: checkout main, fetch origin, reset --hard, then rebase feature branches", kind="fact", age_days=10, importance=0.9, domain="Development"),
                  mem("Force-push with --force-with-lease after rebase, never plain --force", kind="fact", age_days=10, importance=0.85, domain="Development")],
     "noise": {"generator": "filler", "count": 20, "seed": 604},
     "turns": [turn("what is the correct git rebase workflow?", ["$0", "$1"], ["reset --hard", "force-with-lease"]),
               turn("how do you push after rebasing?", ["$1"], ["force-with-lease"]),
               turn("what is the sequence for updating main?", ["$0"], ["checkout main", "reset --hard"])]},
    {"id": "procedural_cron_01", "category": "procedural",
     "memories": [mem("Cron jobs use skip_memory=True and write via entropicmem_cron_remember.py", kind="fact", age_days=30, importance=0.9, domain="Operations"),
                  mem("Never use interactive memory tools from cron — always script-only writes", kind="fact", age_days=30, importance=0.8, domain="Operations")],
     "noise": {"generator": "filler", "count": 20, "seed": 605},
     "turns": [turn("how do crons write to memory?", ["$0"], ["entropicmem_cron_remember"]),
               turn("what must cron jobs avoid?", ["$1"], ["interactive memory tools"]),
               turn("what is the cron memory rule?", ["$0", "$1"], ["skip_memory=True", "script-only"])]},
]

# ─── Scale (5 scenarios) ───
scale = [
    {"id": "scale_memory_count_01", "category": "scale",
     "memories": [mem("The memory vault has 2,157 of 2,200 chars used across core + user profiles", kind="fact", age_days=1, importance=0.9, domain="System"),
                  mem("When memory fills, consolidate stale entries rather than skipping saves", kind="fact", age_days=1, importance=0.8, domain="System")],
     "noise": {"generator": "filler", "count": 20, "seed": 901},
     "turns": [turn("how much memory is used?", ["$0"], ["2,157", "2,200"]),
               turn("what to do when memory is full?", ["$1"], ["consolidate"]),
               turn("what is the memory character budget?", ["$0"], ["2,200"])]},
    {"id": "scale_db_size_01", "category": "scale",
     "memories": [mem("The EntropicMem vault stores facts with FTS5 indexing for fast retrieval", kind="fact", age_days=30, importance=0.7, domain="System"),
                  mem("Fact count grows linearly with sessions; use entropicmem_consolidate to archive old low-access facts", kind="fact", age_days=30, importance=0.7, domain="System")],
     "noise": {"generator": "filler", "count": 20, "seed": 902},
     "turns": [turn("what indexing does EntropicMem use?", ["$0"], ["FTS5"]),
               turn("how to manage fact growth?", ["$1"], ["consolidate"]),
               turn("what happens to fact count?", ["$1"], ["linearly"])]},
    {"id": "scale_worktree_01", "category": "scale",
     "memories": [mem("There should be at most 3 active worktrees per feature branch", kind="fact", age_days=1, importance=0.9, domain="Development"),
                  mem("Prune stale worktrees with git worktree remove --force after PR merge", kind="fact", age_days=1, importance=0.8, domain="Development")],
     "noise": {"generator": "filler", "count": 20, "seed": 903},
     "turns": [turn("how many active worktrees per feature?", ["$0"], ["3"]),
               turn("how to clean up worktrees?", ["$1"], ["worktree remove", "force"]),
               turn("when to prune worktrees?", ["$1"], ["PR merge"])]},
    {"id": "scale_box_01", "category": "scale",
     "memories": [mem("The dev box is swap-pinned at 100% with 7.8 GB RAM, limiting concurrency to 1", kind="fact", age_days=1, importance=0.9, domain="System"),
                  mem("Parallel agents exhaust swap on this box; single-agent sequential execution is required", kind="fact", age_days=1, importance=0.9, domain="Operations")],
     "noise": {"generator": "filler", "count": 20, "seed": 904},
     "turns": [turn("what is the RAM limit?", ["$0"], ["7.8 GB"]),
               turn("why is concurrency limited?", ["$1"], ["swap"]),
               turn("what causes resource exhaustion?", ["$0", "$1"], ["swap", "parallel agents"])]},
    {"id": "scale_noise_01", "category": "scale",
     "memories": [mem("The user's favorite color is blue", kind="preference", age_days=365, importance=0.6, domain="Personal")],
     "noise": {"generator": "filler", "count": 5000, "seed": 905},
     "turns": [turn("what is the user's favorite color?", ["$0"], ["blue"]),
               turn("what color does the user prefer?", ["$0"], ["blue"]),
               turn("which color does the user like most?", ["$0"], ["blue"])]},
]

# ─── Entity (5 scenarios) ───
entity = [
    {"id": "entity_org_01", "category": "entity",
     "memories": [mem("Acme Corp is a leading provider of enterprise mobility solutions in Africa", kind="fact", age_days=100, importance=0.9, domain="Work"),
                  mem("The company was founded in 2005 and has offices in Johannesburg and Cape Town", kind="fact", age_days=100, importance=0.8, domain="Work")],
     "noise": {"generator": "filler", "count": 20, "seed": 701},
     "turns": [turn("what do we know about Acme Corp?", ["$0"], ["enterprise mobility solutions", "Africa"]),
               turn("tell me about Acme Corp", ["$0"], ["enterprise mobility solutions", "Africa"]),
               turn("what is Acme Corp known for?", ["$0"], ["enterprise mobility solutions", "Africa"])]},
    {"id": "entity_project_01", "category": "entity",
     "memories": [mem("Project Orion aims to reduce latency by 40% through edge computing", kind="fact", age_days=60, importance=0.85, domain="Work"),
                  mem("The project is sponsored by the research division and involves three teams", kind="fact", age_days=60, importance=0.75, domain="Work")],
     "noise": {"generator": "filler", "count": 20, "seed": 702},
     "turns": [turn("what do we know about Project Orion?", ["$0"], ["reduce latency by 40%", "edge computing"]),
               turn("tell me about Project Orion", ["$0"], ["reduce latency by 40%", "edge computing"]),
               turn("what is the goal of Project Orion?", ["$0"], ["reduce latency by 40%", "edge computing"])]},
    {"id": "entity_person_01", "category": "entity",
     "memories": [mem("Robin (R. Example) works as a Product Manager at Acme Corp", kind="fact", age_days=30, importance=0.95, domain="People"),
                  mem("His birthday is May 2 and he supports FC Example football club", kind="fact", age_days=30, importance=0.8, domain="People")],
     "noise": {"generator": "filler", "count": 20, "seed": 703},
     "turns": [turn("what do we know about Ufonik?", ["$0"], ["Product Manager", "Acme Corp", "May 2", "FC Example"]),
               turn("tell me about Ufonik", ["$0"], ["Product Manager", "Acme Corp", "May 2", "FC Example"]),
               turn("what is Ufonik's role and employer?", ["$0"], ["Product Manager", "Acme Corp"])]},
    {"id": "entity_product_01", "category": "entity",
     "memories": [mem("EntropicMem is an autonomous AI agent memory layer with full vault integration", kind="fact", age_days=10, importance=0.9, domain="Products"),
                  mem("It uses the EntropicMem vault engine for persistence and supports dual-write to Obsidian", kind="fact", age_days=10, importance=0.85, domain="Products")],
     "noise": {"generator": "filler", "count": 20, "seed": 704},
     "turns": [turn("what is EntropicMem?", ["$0"], ["memory layer", "vault integration"]),
               turn("tell me about EntropicMem", ["$0"], ["memory layer", "vault integration"]),
               turn("what does EntropicMem do?", ["$0"], ["memory layer", "vault integration"])]},
    {"id": "entity_tool_01", "category": "entity",
     "memories": [mem("linuxbrew is installed at /home/linuxbrew/.linuxbrew/bin and is not on the cron PATH", kind="fact", age_days=5, importance=0.8, domain="System"),
                  mem("The Hermes desktop app supports Signal delivery for credential distribution", kind="fact", age_days=5, importance=0.7, domain="System")],
     "noise": {"generator": "filler", "count": 20, "seed": 705},
     "turns": [turn("where is linuxbrew installed?", ["$0"], ["/home/linuxbrew/.linuxbrew/bin"]),
               turn("what is the linuxbrew path?", ["$0"], ["/home/linuxbrew/.linuxbrew/bin"]),
               turn("how do scripts access linuxbrew?", ["$0"], ["/home/linuxbrew/.linuxbrew/bin"])]},
]

# ─── Long content (5 scenarios) ───
long_content = [
    {"id": "long_content_tech_01", "category": "long_content",
     "memories": [mem("The user provided a 500-word technical fact about REST API design: Representational State Transfer (REST) is an architectural style for distributed systems that relies on a stateless, client-server, cacheable communications protocol typically HTTP. REST is not a standard or a protocol, but an architectural style that uses HTTP methods explicitly and in a way that matches the protocol's definition. The basic principles of REST include: 1) Resources are identified by URIs, 2) Resources are manipulated via representations, 3) Self-descriptive messages, 4) Hypermedia as the engine of application state. RESTful applications use HTTP requests to perform CRUD operations. REST is widely used in web services due to its simplicity and scalability.", kind="fact", age_days=10, importance=0.8, domain="Technology")],
     "noise": {"generator": "filler", "count": 20, "seed": 801},
     "turns": [turn("what did the user say about REST API design?", ["$0"], ["Representational State Transfer", "architectural style"]),
               turn("what is the user's technical fact about REST?", ["$0"], ["Representational State Transfer", "architectural style"]),
               turn("what did the user tell me about REST?", ["$0"], ["Representational State Transfer", "architectural style"])]},
    {"id": "long_content_tech_02", "category": "long_content",
     "memories": [mem("The user shared a detailed explanation of quantum entanglement: Quantum entanglement is a physical phenomenon that occurs when a pair or group of particles is generated, interact, or share spatial proximity in a way such that the quantum state of each particle cannot be described independently of the state of the others, even when the particles are separated by a large distance. The topic of quantum entanglement is at the heart of the disparity between classical and quantum physics: entanglement is a primary feature of quantum mechanics not present in classical mechanics.", kind="fact", age_days=15, importance=0.75, domain="Science")],
     "noise": {"generator": "filler", "count": 20, "seed": 802},
     "turns": [turn("what did the user say about quantum entanglement?", ["$0"], ["quantum entanglement", "physical phenomenon"]),
               turn("what is the user's explanation of quantum entanglement?", ["$0"], ["quantum entanglement", "physical phenomenon"]),
               turn("what did the user tell me about quantum entanglement?", ["$0"], ["quantum entanglement", "physical phenomenon"])]},
    {"id": "long_content_tech_03", "category": "long_content",
     "memories": [mem("The user described the process of photosynthesis: Photosynthesis is the process used by plants, algae and certain bacteria to harness energy from sunlight and turn it into chemical energy. During photosynthesis, plants take in carbon dioxide (CO2) and water (H2O) from the air and soil. Within the plant cell, the water is oxidized, meaning it loses electrons, while the carbon dioxide is reduced, meaning it gains electrons. This transforms the water into oxygen and the carbon dioxide into glucose. The plant then releases the oxygen back into the air, and stores energy within the glucose molecules.", kind="fact", age_days=20, importance=0.7, domain="Science")],
     "noise": {"generator": "filler", "count": 20, "seed": 803},
     "turns": [turn("what did the user say about photosynthesis?", ["$0"], ["plants", "sunlight", "chemical energy", "carbon dioxide", "water"]),
               turn("what is the user's explanation of photosynthesis?", ["$0"], ["plants", "sunlight", "chemical energy", "carbon dioxide", "water"]),
               turn("what did the user tell me about photosynthesis?", ["$0"], ["plants", "sunlight", "chemical energy", "carbon dioxide", "water"])]},
    {"id": "long_content_tech_04", "category": "long_content",
     "memories": [mem("The user explained blockchain consensus: A blockchain is a distributed ledger that maintains a continuously growing list of records called blocks, linked using cryptography. Each block contains a cryptographic hash of the previous block, a timestamp, and transaction data. Bitcoin uses a proof-of-work consensus mechanism to add new blocks approximately every 10 minutes. The decentralized nature of blockchain means no single entity controls the network, and consensus is achieved when the majority of nodes agree on the state of the ledger.", kind="fact", age_days=12, importance=0.75, domain="Technology")],
     "noise": {"generator": "filler", "count": 20, "seed": 804},
     "turns": [turn("what did the user explain about blockchain?", ["$0"], ["distributed ledger", "cryptography", "consensus"]),
               turn("what is the user's blockchain explanation?", ["$0"], ["distributed ledger", "cryptography", "consensus"]),
               turn("what did the user tell me about blockchain consensus?", ["$0"], ["distributed ledger", "cryptography", "consensus"])]},
    {"id": "long_content_tech_05", "category": "long_content",
     "memories": [mem("The user described distributed systems theory: A distributed system is a computer system with which information is communicated between the sequential processes running on multiple computers. Distributed systems are systems in which hardware to support distributed communication is not distinguishable from the kind of computing involved, so the system as a whole can be considered as that which is not distributed, but whose correctness depends on the timing of events.", kind="fact", age_days=8, importance=0.8, domain="Technology")],
     "noise": {"generator": "filler", "count": 20, "seed": 805},
     "turns": [turn("what did the user say about distributed systems?", ["$0"], ["distributed system", "multiple computers"]),
               turn("what is the user's explanation of distributed systems?", ["$0"], ["distributed system", "multiple computers"]),
               turn("what did the user tell me about distributed computing?", ["$0"], ["distributed system", "multiple computers"])]},
]

# ─── Abstention (5 scenarios) ───
abstention = [
    {"id": "abstention_junk_01", "category": "abstention",
     "memories": [mem("The user's favorite tea is rooibos", kind="profile", age_days=10, importance=0.5, domain="Personal")],
     "noise": {"generator": "filler", "count": 200, "seed": 9},
     "turns": [turn("zzqx nonsense a", [], [], ["$noise"]),
               turn("blorf gibberish b", [], [], ["$noise"]),
               turn("quux foobar c", [], [], ["$noise"])]},
    {"id": "abstention_unrelated_01", "category": "abstention",
     "memories": [mem("The user bakes sourdough every Sunday", kind="fact", age_days=12, importance=0.5, domain="Leisure")],
     "noise": {"generator": "filler", "count": 150, "seed": 12},
     "turns": [turn("what is orbital decay of a geosynchronous satellite?", [], [], ["$noise"]),
               turn("how does a tokamak confine plasma?", [], [], ["$noise"]),
               turn("what is the Schwarzschild radius of a black hole?", [], [], ["$noise"])]},
    {"id": "abstention_random_01", "category": "abstention",
     "memories": [mem('The user\'s favorite book is "To Kill a Mockingbird"', kind="fact", age_days=20, importance=0.6, domain="Leisure")],
     "noise": {"generator": "filler", "count": 100, "seed": 13},
     "turns": [turn("what is the airspeed velocity of an unladen swallow?", [], [], ["$noise"]),
               turn("how many roads must a man walk down?", [], [], ["$noise"]),
               turn("what is the answer to life, the universe, and everything?", [], [], ["$noise"])]},
    {"id": "abstention_math_01", "category": "abstention",
     "memories": [mem("The user's favorite number is pi (approximately 3.14159)", kind="fact", age_days=180, importance=0.5, domain="Personal")],
     "noise": {"generator": "filler", "count": 50, "seed": 14},
     "turns": [turn("what was the last conversation about?", [], [], ["$noise"]),
               turn("can you tell me a random number?", [], [], ["$noise"]),
               turn("what did I ask about three minutes ago?", [], [], ["$noise"])]},
    {"id": "abstention_geo_01", "category": "abstention",
     "memories": [mem("The user is interested in learning about Mars colonization", kind="fact", age_days=30, importance=0.4, domain="Personal")],
     "noise": {"generator": "filler", "count": 75, "seed": 15},
     "turns": [turn("what is the capital city of Atlantis?", [], [], ["$noise"]),
               turn("where is the fictional city of El Dorado located?", [], [], ["$noise"]),
               turn("what is the highest mountain on the Moon?", [], [], ["$noise"])]},
]

datasets = {
    "paraphrase": paraphrase,
    "ageing": ageing,
    "update": update,
    "contradiction": contradiction,
    "multi_user": multi_user,
    "multimodal": multimodal,
    "procedural": procedural,
    "scale": scale,
    "entity": entity,
    "long_content": long_content,
    "abstention": abstention,
}

for cat, scenarios in datasets.items():
    filepath = HARD_DIR / f"{cat}.jsonl"
    with open(filepath, "w") as f:
        for s in scenarios:
            f.write(json.dumps(s, ensure_ascii=False) + "\n")
    print(f"Written {len(scenarios)} scenarios to {filepath}")

total = sum(len(s) for s in datasets.values())
queries = total * 3
print(f"\nTotal scenarios: {total} ({len(datasets)} categories)")
print(f"Total queries: {queries}")
