"""Generate tiny synthetic v2.x fixture DBs for EM-203 migration tests.

The card requires fixtures "generated by v2.3, v2.5 and v2.7 code". This script
honours that literally: for each release it extracts that commit's tree with
``git archive``, then runs the REAL historical ``memory_engine.MemoryEngine``
against a fresh temp DB so the schema is whatever that release actually wrote.

An earlier version of this script reconstructed the schema by regex-scraping
historical ``MEMORY_SCHEMA`` constants. That was measurably wrong: it produced
``embeddings`` and ``facts_archive`` tables that real v2.7.0 code does not
create (embeddings needs optional deps; facts_archive is created lazily by
``consolidate()``). Do not go back to scraping; execute the real thing.

Regenerate with::

    python tests/fixtures/db/generate_fixtures.py

Requires git history access. Outputs are tiny, synthetic, and committed so CI
needs neither git history nor the historical imports.
"""

from __future__ import annotations

import json
import os
import shutil
import sqlite3
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parent

# version label -> commit whose plugin.yaml first carried that version
TARGETS = [
    ("2.3.0", "6bc23c5aeeb920065909c52bb738c82db39cbc2a"),
    ("2.5.0", "73a36af72d2cc0418216f141bb07dc499fbc7ef8"),
    ("2.7.0", "567aa000243a525f2b8f8f75c05c593178885e7e"),
]

# Engine directory moved from skills/ to plugins/ at v2.7.0.
ENGINE_DIRS = [
    "plugins/entropicmem/scripts",
    "skills/entropicmem/scripts",
]

# Synthetic rows only: generic placeholders, never real memory content.
SEED_FACTS = [
    ("syn_a1", "synthetic fixture fact one", "Knowledge", 0.5),
    ("syn_b2", "synthetic fixture fact two", "Testing", 0.9),
]

# Runs inside the extracted historical tree with its own PYTHONPATH.
_BUILD_SNIPPET = r"""
import json, sqlite3, sys
from pathlib import Path

db_path = Path(sys.argv[1])
seed = json.loads(sys.argv[2])

import memory_engine  # the REAL historical module

# Constructing the engine runs that release's _init_schema(): the schema under
# test is therefore exactly what this version wrote, not an approximation.
engine = memory_engine.MemoryEngine(db_path)

conn = engine.db
cols = [r[1] for r in conn.execute("PRAGMA table_info(facts)")]
for fid, content, domain, imp in seed:
    names = ["id", "content", "domain", "importance"]
    vals = [fid, content, domain, imp]
    if "deleted" in cols:
        names.append("deleted")
        vals.append(0)
    conn.execute(
        "INSERT OR REPLACE INTO facts (%s) VALUES (%s)"
        % (", ".join(names), ", ".join("?" * len(names))),
        vals,
    )
conn.commit()

# Keep facts_fts consistent the way the engine itself does (a v2 delete path
# that skipped FTS cleanup is a known hazard, so never emit an inconsistent
# fixture). Prefer the engine's own rebuild.
if hasattr(engine, "_rebuild_fts"):
    engine._rebuild_fts()
    conn.commit()

conn.close()
print(json.dumps({"ok": True}))
"""


def _extract(commit: str, dest: Path) -> None:
    out = subprocess.run(
        ["git", "-C", str(REPO), "archive", commit],
        capture_output=True,
        check=False,
    )
    if out.returncode != 0:
        raise SystemExit(f"git archive {commit} failed: {out.stderr.decode().strip()}")
    subprocess.run(["tar", "-x", "-C", str(dest)], input=out.stdout, check=True)


def _find_engine_dir(root: Path) -> Path:
    for rel in ENGINE_DIRS:
        cand = root / rel
        if (cand / "memory_engine.py").is_file():
            return cand
    raise SystemExit(f"no engine dir under {root}")


def build(version: str, commit: str, dest: Path) -> dict:
    tmp = Path(tempfile.mkdtemp(prefix=f"em-fix-{version.replace('.', '')}-"))
    try:
        _extract(commit, tmp)
        engine_dir = _find_engine_dir(tmp)
        raw_db = tmp / "fixture.db"

        env = dict(os.environ)
        env["PYTHONPATH"] = str(engine_dir)
        # Belt and braces: the historical engine reads these, and a leaked
        # value here would point a fixture build at the LIVE store.
        env["ENTROPICMEM_MEMORY_DB"] = str(raw_db)
        env["ENTROPICMEM_INDEX_DB"] = str(tmp / "index.db")
        env["ENTROPICMEM_VAULT_PATH"] = str(tmp / "vault")
        (tmp / "vault").mkdir(exist_ok=True)

        proc = subprocess.run(
            [
                sys.executable,
                "-c",
                _BUILD_SNIPPET,
                str(raw_db),
                json.dumps(SEED_FACTS),
            ],
            capture_output=True,
            text=True,
            cwd=str(tmp),
            env=env,
            check=False,
        )
        if proc.returncode != 0:
            raise SystemExit(
                f"historical engine failed for v{version} ({commit[:8]}):\n"
                f"{proc.stdout}\n{proc.stderr}"
            )

        # Shrink: only a couple of rows, so a small page size + VACUUM keeps
        # the committed fixtures genuinely tiny.
        if dest.exists():
            dest.unlink()
        src = sqlite3.connect(raw_db)
        try:
            src.execute("PRAGMA page_size=512")
            src.execute("VACUUM INTO ?", (str(dest),))
        finally:
            src.close()

        conn = sqlite3.connect(dest)
        try:
            info = {
                "user_version": conn.execute("PRAGMA user_version").fetchone()[0],
                "page_size": conn.execute("PRAGMA page_size").fetchone()[0],
                "integrity": conn.execute("PRAGMA integrity_check").fetchone()[0],
                "facts": conn.execute("SELECT COUNT(*) FROM facts").fetchone()[0],
                "fts_rows": (
                    conn.execute("SELECT COUNT(*) FROM facts_fts").fetchone()[0]
                    if conn.execute(
                        "SELECT 1 FROM sqlite_master WHERE name='facts_fts'"
                    ).fetchone()
                    else 0
                ),
                "tables": sorted(
                    r[0]
                    for r in conn.execute(
                        "SELECT name FROM sqlite_master WHERE type='table' "
                        "AND name NOT LIKE 'sqlite_%' AND name NOT LIKE '%_fts_%'"
                    )
                ),
                "facts_cols": sorted(
                    r[1] for r in conn.execute("PRAGMA table_info(facts)")
                ),
            }
        finally:
            conn.close()
        return info
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def main() -> int:
    for version, commit in TARGETS:
        dest = HERE / f"v{version.replace('.', '_')}.db"
        info = build(version, commit, dest)
        print(f"{version} ({commit[:8]}) -> {dest.name} ({dest.stat().st_size} B)")
        print(
            f"   user_version={info['user_version']} page_size={info['page_size']} "
            f"integrity={info['integrity']} facts={info['facts']} "
            f"fts_rows={info['fts_rows']}"
        )
        print(f"   tables={info['tables']}")
        print(f"   facts_cols={info['facts_cols']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
