"""EM-203 — migration framework.

Card AC:
* fixture DBs generated by v2.3, v2.5 and v2.7 code all migrate to LATEST
* re-running is a no-op
* failure mid-migration leaves the DB at the previous version (injected)

Plus the owner's standing rule for this sprint: the framework must never
auto-run against a DB outside a temp or test path during development. The
guard tests below assert that refusal WITHOUT opening any file, so they can
never touch the live store.
"""

from __future__ import annotations

import hashlib
import shutil
import sqlite3
import subprocess
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "plugins" / "entropicmem" / "scripts"))

from em.store import db as emdb  # noqa: E402
from em.store import migrations as emmig  # noqa: E402

FIXTURES = Path(__file__).resolve().parent.parent / "fixtures" / "db"

V2_FIXTURES = ["v2_3_0.db", "v2_5_0.db", "v2_7_0.db"]


def _uv(conn: sqlite3.Connection) -> int:
    return conn.execute("PRAGMA user_version").fetchone()[0]


def _table_set(conn: sqlite3.Connection) -> set:
    return {
        r[0]
        for r in conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' "
            "AND name NOT LIKE 'sqlite_%'"
        )
    }


def _fact_ids(conn: sqlite3.Connection) -> set:
    return {r[0] for r in conn.execute("SELECT id FROM facts")}


def _copy_fixture(name: str, dest: Path) -> Path:
    """Copy a committed fixture into ``dest``.

    A missing fixture is a hard error, not a skip: these are committed to the
    repo, so their absence means the checkout is broken and silently skipping
    would make the card's main acceptance criterion vacuous in CI.
    """
    src = FIXTURES / name
    if not src.is_file():
        raise AssertionError(
            f"missing committed fixture {src}. Regenerate with: "
            "python tests/fixtures/db/generate_fixtures.py"
        )
    target = dest / name
    shutil.copyfile(src, target)
    return target


def test_fixtures_are_present_in_the_checkout():
    """Guard the guard: the AC fixtures must actually be committed."""
    missing = [name for name in V2_FIXTURES if not (FIXTURES / name).is_file()]
    assert not missing, (
        f"fixtures missing from the checkout: {missing}. They are committed on "
        "purpose so CI needs no git history; run "
        "tests/fixtures/db/generate_fixtures.py to recreate them."
    )


def test_fixtures_are_tiny_and_synthetic():
    """No real memory data may ever be committed as a fixture."""
    for name in V2_FIXTURES:
        path = FIXTURES / name
        conn = sqlite3.connect(path)
        try:
            rows = conn.execute("SELECT id, content FROM facts").fetchall()
            assert len(rows) == 2, f"{name}: expected exactly the 2 synthetic rows"
            for fid, content in rows:
                assert fid.startswith("syn_"), f"{name}: unexpected fact id {fid!r}"
                assert "synthetic fixture" in content, f"{name}: {content!r}"
        finally:
            conn.close()


# ── registry ────────────────────────────────────────────────────────────────


def test_registry_discovers_numbered_modules_in_version_order():
    registry = emmig.discover()
    assert [m.version for m in registry] == sorted(m.version for m in registry)
    assert registry, "no migrations discovered"
    # One discovered Migration per numbered file on disk.
    assert len(registry) == len(_module_files())
    for m, path in zip(registry, _module_files()):
        assert path.name == f"{m.version:04d}_{m.slug}.py"


def _module_files() -> list:
    d = Path(emmig.__file__).resolve().parent
    return sorted(d.glob("[0-9][0-9][0-9][0-9]_*.py"))


def test_each_module_exposes_required_attributes():
    for m in emmig.discover():
        assert isinstance(m.version, int) and m.version >= 1
        assert isinstance(m.name, str) and m.name
        assert callable(m.up)
        assert len(m.checksum) == 64  # sha256 hex


def test_filename_number_matches_module_VERSION():
    for m in emmig.discover():
        stem = m.module_name.rsplit(".", 1)[-1]
        assert stem.startswith(f"{m.version:04d}_"), f"{m.name} vs VERSION {m.version}"


def test_versions_are_unique_and_contiguous_from_one():
    versions = [m.version for m in emmig.discover()]
    assert versions == list(range(1, len(versions) + 1)), versions


def test_latest_derives_from_registry():
    assert emmig.LATEST == max(m.version for m in emmig.discover())


def test_checksum_is_sha256_of_module_source():
    m = emmig.discover()[0]
    src = Path(
        Path(emmig.__file__).resolve().parent / f"{m.version:04d}_{m.slug}.py"
    ).read_bytes()
    assert m.checksum == hashlib.sha256(src).hexdigest()


def test_checksum_is_stable_across_discovery_calls():
    first = {m.version: m.checksum for m in emmig.discover()}
    second = {m.version: m.checksum for m in emmig.discover()}
    assert first == second


# ── AC: v2.x fixtures migrate to LATEST ─────────────────────────────────────


@pytest.mark.parametrize("fixture", V2_FIXTURES)
def test_v2_fixture_migrates_to_latest(tmp_path, fixture):
    path = _copy_fixture(fixture, tmp_path)
    conn = emdb.open_db(path)
    try:
        before = _fact_ids(conn)
        assert _uv(conn) == 0, "v2 stores never set user_version"

        applied = emmig.migrate(conn)

        assert _uv(conn) == emmig.LATEST
        assert [m.version for m in applied] == list(
            range(1, emmig.LATEST + 1)
        ), "every pending migration must run"
        # Data survives: the v2 facts are still addressable by legacy id.
        assert before <= _fact_ids(conn)
        assert "schema_migrations" in _table_set(conn)
    finally:
        conn.close()


@pytest.mark.parametrize("fixture", V2_FIXTURES)
def test_migrated_fixture_keeps_v2_tables_readable(tmp_path, fixture):
    """0001 brings a v2 DB to the exact v2.7 shape; it must not drop anything."""
    path = _copy_fixture(fixture, tmp_path)
    conn = emdb.open_db(path)
    try:
        emmig.migrate(conn)
        tables = _table_set(conn)
        for required in ("facts", "episodes", "triples", "audit_log", "pending_facts"):
            assert required in tables, f"{required} lost by migration"
        cols = {r[1] for r in conn.execute("PRAGMA table_info(facts)")}
        for required in ("version", "deleted", "profile_id", "sensitivity"):
            assert required in cols, f"facts.{required} missing after migration"
        assert conn.execute("PRAGMA integrity_check").fetchone()[0] == "ok"
    finally:
        conn.close()


def test_empty_db_migrates_to_latest(tmp_path):
    """An empty DB is a valid starting point (card: 'or empty DB')."""
    path = tmp_path / "empty.db"
    conn = emdb.open_db(path)
    try:
        emmig.migrate(conn)
        assert _uv(conn) == emmig.LATEST
        assert "facts" in _table_set(conn)
    finally:
        conn.close()


def test_in_memory_db_migrates_without_backup():
    conn = emdb.open_db(":memory:")
    try:
        emmig.migrate(conn)
        assert _uv(conn) == emmig.LATEST
    finally:
        conn.close()


# ── AC: re-running is a no-op ───────────────────────────────────────────────


def test_rerun_is_a_noop(tmp_path):
    path = _copy_fixture("v2_7_0.db", tmp_path)
    conn = emdb.open_db(path)
    try:
        emmig.migrate(conn)
        rows1 = conn.execute("SELECT * FROM schema_migrations").fetchall()

        applied = emmig.migrate(conn)

        assert applied == []
        assert conn.execute("SELECT * FROM schema_migrations").fetchall() == rows1
        assert _uv(conn) == emmig.LATEST
    finally:
        conn.close()


def test_rerun_idempotent_many_times(tmp_path):
    path = tmp_path / "repeat.db"
    conn = emdb.open_db(path)
    try:
        for _ in range(5):
            emmig.migrate(conn)
        assert _uv(conn) == emmig.LATEST
        assert conn.execute("SELECT COUNT(*) FROM schema_migrations").fetchone()[0] == (
            emmig.LATEST
        )
    finally:
        conn.close()


def test_partially_migrated_db_resumes_from_where_it_stopped(tmp_path):
    """A crash after migration 1 must not re-apply it (it picks up at 2)."""
    path = tmp_path / "partial.db"
    conn = emdb.open_db(path)
    calls: list = []

    def up_one(c):
        calls.append(1)
        c.execute("CREATE TABLE step_one (id INTEGER PRIMARY KEY)")

    def up_two(c):
        calls.append(2)
        c.execute("CREATE TABLE step_two (id INTEGER PRIMARY KEY)")

    registry = [
        emmig.Migration(
            version=1, name="one", slug="one", up=up_one, checksum="1" * 64
        ),
        emmig.Migration(
            version=2, name="two", slug="two", up=up_two, checksum="2" * 64
        ),
    ]
    try:
        emmig.migrate(conn, registry=registry, target=1)
        assert _uv(conn) == 1
        assert calls == [1]

        applied = emmig.migrate(conn, registry=registry)

        assert [m.version for m in applied] == [2], "must not re-apply version 1"
        assert calls == [1, 2]
        assert _uv(conn) == 2
        assert {"step_one", "step_two"} <= _table_set(conn)
    finally:
        conn.close()


# ── AC: failure mid-migration leaves DB at previous version ─────────────────


def test_failure_mid_migration_leaves_previous_version(tmp_path):
    """Injected exception: version, bookkeeping and DDL all roll back."""
    path = tmp_path / "boom.db"
    conn = emdb.open_db(path)
    boom_marker = "zz_boom_marker_table"

    class Boom(RuntimeError):
        pass

    def up_ok(c):
        c.execute("CREATE TABLE zz_ok (id INTEGER PRIMARY KEY)")

    def up_boom(c):
        # Create something then fail: if the txn is real, this vanishes.
        c.execute(f"CREATE TABLE {boom_marker} (id INTEGER PRIMARY KEY)")
        raise Boom("injected")

    registry = [
        emmig.Migration(
            version=1, name="ok", slug="ok", up=up_ok, checksum="a" * 64
        ),
        emmig.Migration(
            version=2, name="boom", slug="boom", up=up_boom, checksum="b" * 64
        ),
    ]
    try:
        with pytest.raises(Boom):
            emmig.migrate(conn, registry=registry)

        assert _uv(conn) == 1, "version must stay at the last GOOD migration"
        tables = _table_set(conn)
        assert "zz_ok" in tables, "the successful migration must persist"
        assert boom_marker not in tables, "failed migration's DDL must roll back"
        recorded = {
            r[0] for r in conn.execute("SELECT version FROM schema_migrations")
        }
        assert recorded == {1}, f"bookkeeping must not record the failure: {recorded}"
    finally:
        conn.close()


def test_failure_on_first_migration_leaves_version_zero(tmp_path):
    path = tmp_path / "boom0.db"
    conn = emdb.open_db(path)

    class Boom(RuntimeError):
        pass

    def up_boom(c):
        c.execute("CREATE TABLE zz_nope (id INTEGER PRIMARY KEY)")
        raise Boom("injected")

    registry = [
        emmig.Migration(
            version=1, name="boom", slug="boom", up=up_boom, checksum="b" * 64
        )
    ]
    try:
        with pytest.raises(Boom):
            emmig.migrate(conn, registry=registry)
        assert _uv(conn) == 0
        assert "zz_nope" not in _table_set(conn)
        assert conn.execute("SELECT COUNT(*) FROM schema_migrations").fetchone()[0] == 0
    finally:
        conn.close()


def test_user_version_pragma_is_transactional(tmp_path):
    """The rollback guarantee depends on user_version being transactional."""
    path = tmp_path / "txn.db"
    conn = emdb.open_db(path)
    try:
        conn.execute("PRAGMA user_version = 7")
        with pytest.raises(RuntimeError):
            with emdb.write_txn(conn):
                conn.execute("PRAGMA user_version = 9")
                raise RuntimeError("rollback")
        assert _uv(conn) == 7, "user_version did not roll back with the txn"
    finally:
        conn.close()


# ── downgrade refusal ───────────────────────────────────────────────────────


def test_refuses_db_newer_than_code(tmp_path):
    path = tmp_path / "future.db"
    conn = emdb.open_db(path)
    try:
        emmig.migrate(conn)
        conn.execute(f"PRAGMA user_version = {emmig.LATEST + 1}")
        with pytest.raises(emdb.DowngradeError):
            emmig.migrate(conn)
    finally:
        conn.close()


def test_ensure_schema_refuses_newer_db(tmp_path):
    """Integration with EM-202's fast path: same refusal, same error."""
    path = tmp_path / "future2.db"
    conn = emdb.open_db(path)
    try:
        conn.execute(f"PRAGMA user_version = {emmig.LATEST + 1}")
        with pytest.raises(emdb.DowngradeError):
            emdb.ensure_schema(conn, emmig.migrate)
    finally:
        conn.close()


def test_ensure_schema_runs_migrations_and_fast_paths(tmp_path):
    path = tmp_path / "ens.db"
    conn = emdb.open_db(path)
    try:
        assert emdb.ensure_schema(conn, emmig.migrate) is True
        assert _uv(conn) == emmig.LATEST
        # Second call takes the fast path (no migration work).
        assert emdb.ensure_schema(conn, emmig.migrate) is False
    finally:
        conn.close()


def test_db_latest_tracks_registry():
    """db.LATEST_USER_VERSION must not drift from the migration registry."""
    assert emdb.LATEST_USER_VERSION == emmig.LATEST


def test_db_imported_alone_resolves_latest_lazily():
    """Regression: `import em.store.db` on its own must not treat a migrated
    DB as a downgrade.

    LATEST lives in the registry, which lives in a module that depends on db.
    If db only picked it up via an import side effect, importing db alone would
    leave it at 0 and every real database would fail ensure_schema. Run in a
    fresh interpreter so no other test has imported migrations first.
    """
    script = (
        "import sys;"
        f"sys.path.insert(0, {str(Path(emmig.__file__).resolve().parents[3])!r});"
        "from em.store import db;"
        "assert 'em.store.migrations' not in sys.modules, 'migrations pre-imported';"
        "conn = db.open_db(':memory:');"
        "conn.execute('PRAGMA user_version = %d');"
        "assert db.ensure_schema(conn, lambda c: None) is False, "
        "'a current DB was misread as a downgrade';"
        "print(db.LATEST_USER_VERSION)"
    ) % emmig.LATEST
    out = subprocess.run(
        [sys.executable, "-c", script],
        capture_output=True,
        text=True,
        check=False,
    )
    assert out.returncode == 0, f"lazy resolution failed:\n{out.stdout}\n{out.stderr}"
    assert out.stdout.strip() == str(emmig.LATEST)


def test_ensure_schema_migrates_a_fresh_db_to_latest(tmp_path):
    """Integration: ensure_schema + the registry's migrate reaches LATEST.

    NOTE: this deliberately does NOT claim to cover the lazy-resolution
    regression — obtaining ``migrate`` requires importing
    ``em.store.migrations``, and that import updates ``LATEST_USER_VERSION``
    as a side effect, so the stale-constant case is unreachable here. The
    lazy path is covered by ``test_db_imported_alone_resolves_latest_lazily``,
    which never imports the registry.
    """
    script = (
        "import sys;"
        f"sys.path.insert(0, {str(Path(emmig.__file__).resolve().parents[3])!r});"
        "from em.store import db;"
        "from em.store.migrations import migrate, LATEST;"
        f"conn = db.open_db({str(tmp_path / 'lazy.db')!r});"
        "ran = db.ensure_schema(conn, migrate);"
        "print(int(ran), db.LATEST_USER_VERSION, LATEST,"
        " conn.execute('PRAGMA user_version').fetchone()[0])"
    )
    out = subprocess.run(
        [sys.executable, "-c", script],
        capture_output=True,
        text=True,
        check=False,
    )
    assert out.returncode == 0, f"ensure_schema+migrate failed:\n{out.stdout}\n{out.stderr}"
    ran, db_latest, registry_latest, uv = out.stdout.strip().split()
    assert (ran, db_latest, registry_latest, uv) == (
        "1",
        str(emmig.LATEST),
        str(emmig.LATEST),
        str(emmig.LATEST),
    )


# ── checksum drift detection ────────────────────────────────────────────────


def test_checksum_mismatch_on_applied_migration_is_refused(tmp_path):
    """An edited migration must not silently re-run or pass as applied."""
    path = tmp_path / "drift.db"
    conn = emdb.open_db(path)
    original = emmig.Migration(
        version=1, name="orig", slug="orig", up=lambda c: None, checksum="c" * 64
    )
    try:
        emmig.migrate(conn, registry=[original])
        assert _uv(conn) == 1

        tampered = emmig.Migration(
            version=1,
            name="orig",
            slug="orig",
            up=lambda c: None,
            checksum="d" * 64,  # source changed after it was applied
        )
        with pytest.raises(emmig.MigrationChecksumMismatch):
            emmig.migrate(conn, registry=[tampered, _v2_migration()])
    finally:
        conn.close()


def _v2_migration() -> emmig.Migration:
    return emmig.Migration(
        version=2, name="second", slug="second", up=lambda c: None, checksum="e" * 64
    )


# ── backups ─────────────────────────────────────────────────────────────────


def test_backup_created_before_migrating(tmp_path):
    path = _copy_fixture("v2_7_0.db", tmp_path)
    conn = emdb.open_db(path)
    try:
        emmig.migrate(conn)
    finally:
        conn.close()
    backups = sorted((tmp_path / "backups").glob("pre-migrate-v*-to-*.db"))
    assert backups, "no pre-migration backup written"
    name = backups[-1].name
    assert name.startswith(f"pre-migrate-v0-to-v{emmig.LATEST}-"), name
    # The backup must be the UNMIGRATED database.
    bconn = sqlite3.connect(backups[-1])
    try:
        assert bconn.execute("PRAGMA user_version").fetchone()[0] == 0
        assert bconn.execute("PRAGMA integrity_check").fetchone()[0] == "ok"
    finally:
        bconn.close()


def test_noop_migrate_writes_no_backup(tmp_path):
    path = _copy_fixture("v2_7_0.db", tmp_path)
    conn = emdb.open_db(path)
    try:
        emmig.migrate(conn)
        before = sorted((tmp_path / "backups").glob("*.db"))
        emmig.migrate(conn)
        after = sorted((tmp_path / "backups").glob("*.db"))
        assert before == after, "a no-op run must not write another backup"
    finally:
        conn.close()


def test_backup_dir_is_overridable(tmp_path):
    path = tmp_path / "o.db"
    custom = tmp_path / "elsewhere"
    conn = emdb.open_db(path)
    try:
        emmig.migrate(conn, backup_dir=custom)
    finally:
        conn.close()
    assert list(custom.glob("pre-migrate-*.db")), "custom backup_dir not used"


# ── safety guard: never auto-run outside temp/test paths ────────────────────
#
# These assert on a pure path predicate. They open NO connection and touch NO
# file, so they cannot modify the live store even by accident.


def test_guard_refuses_the_real_live_store_path():
    live = Path.home() / ".hermes" / "entropicmem" / "memory.db"
    with pytest.raises(emmig.MigrationRefused):
        emmig.assert_safe_db_path(live)


def test_guard_refuses_any_path_under_the_live_entropicmem_dir():
    for name in ("memory.db", "index.db", "something-else.db"):
        live = Path.home() / ".hermes" / "entropicmem" / name
        with pytest.raises(emmig.MigrationRefused):
            emmig.assert_safe_db_path(live)


def test_guard_refuses_live_store_even_via_a_relative_path(tmp_path, monkeypatch):
    """`~/.hermes/entropicmem/../entropicmem/memory.db` must still be caught."""
    sneaky = Path.home() / ".hermes" / "entropicmem" / ".." / "entropicmem" / "memory.db"
    with pytest.raises(emmig.MigrationRefused):
        emmig.assert_safe_db_path(sneaky)


def test_guard_refuses_a_home_dir_db():
    with pytest.raises(emmig.MigrationRefused):
        emmig.assert_safe_db_path(Path.home() / "notes.db")


def test_guard_allows_temp_paths(tmp_path):
    emmig.assert_safe_db_path(tmp_path / "x.db")  # must not raise
    emmig.assert_safe_db_path(":memory:")
    emmig.assert_safe_db_path("")


def test_guard_allows_repo_test_paths():
    emmig.assert_safe_db_path(FIXTURES / "v2_7_0.db")
    emmig.assert_safe_db_path(
        Path(__file__).resolve().parents[2] / "tests" / "tmp" / "x.db"
    )


def test_guard_can_be_explicitly_overridden_for_the_live_store():
    """The opt-in exists for the real 3.0 cutover; dev never sets it."""
    import os

    live = Path.home() / ".hermes" / "entropicmem" / "memory.db"
    with pytest.raises(emmig.MigrationRefused):
        emmig.assert_safe_db_path(live)
    os.environ[emmig.ALLOW_LIVE_ENV] = "1"
    try:
        emmig.assert_safe_db_path(live)  # must not raise now
    finally:
        del os.environ[emmig.ALLOW_LIVE_ENV]
    with pytest.raises(emmig.MigrationRefused):
        emmig.assert_safe_db_path(live)


def test_migrate_refuses_live_store_before_touching_anything(monkeypatch):
    """The runner must check the path BEFORE opening or backing up."""
    opened: list = []
    real_connect = sqlite3.connect

    def spy_connect(*a, **k):
        opened.append(a[0] if a else k.get("database"))
        return real_connect(*a, **k)

    conn = emdb.open_db(":memory:")
    try:
        monkeypatch.setattr(sqlite3, "connect", spy_connect)
        monkeypatch.setattr(
            emmig,
            "_db_path_of",
            lambda c: str(Path.home() / ".hermes" / "entropicmem" / "memory.db"),
        )
        with pytest.raises(emmig.MigrationRefused):
            emmig.migrate(conn)
        assert opened == [], "guard fired only after a connection was opened"
        assert _uv(conn) == 0, "a refused run must not migrate anything"
    finally:
        conn.close()
